//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub mod prelude;

pub mod permission_role;
pub mod permission_user;
pub mod permissions;
pub mod role_user;
pub mod roles;
pub mod tokens;
pub mod users;
