//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub mod prelude;

pub mod permission_role;
pub mod permission_user;
pub mod permissions;
pub mod role_user;
pub mod roles;
pub mod tokens;
pub mod users;
