//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::permission_role::Entity as PermissionRole;
pub use super::permission_user::Entity as PermissionUser;
pub use super::permissions::Entity as Permissions;
pub use super::role_user::Entity as RoleUser;
pub use super::roles::Entity as Roles;
pub use super::tokens::Entity as Tokens;
pub use super::users::Entity as Users;
